server:
  port: 7002
eureka: 
  instance:
    hostname: springcloud02.com
  client: 
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://springcloud01.com:7001/eureka/,http://springcloud03.com:7003/eureka/
      