server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url: 
       defaultZone: http://springcloud02.com:7002/eureka/,http://springcloud03.com:7003/eureka/,http://springcloud01.com:7001/eureka/
feign:
  hystrix: 
   enabled: true